Use uv publish

diff --git a/.github/workflows/build-all-tags.yaml b/.github/workflows/build-all-tags.yaml
--- a/.github/workflows/build-all-tags.yaml
+++ b/.github/workflows/build-all-tags.yaml
@@ -20,20 +20,20 @@ jobs:
         run: git fetch --tags
 
       - name: Install UV
-        uses: astral-sh/setup-uv@v6
+        uses: astral-sh/setup-uv@v7
         with:
-          version: "0.8.15"
+          version: "0.9.2"
           python-version: "3.13"
           activate-environment: true
           enable-cache: false
 
-      - name: Install build tools
+      - name: Install tools
         shell: bash
         run: |
-          uv pip install twine==6.1.0
+          uv pip install keyrings.google-artifactregistry-auth
 
       - id: oidc
-        uses: google-github-actions/auth@v2
+        uses: google-github-actions/auth@v3
         with:
           credentials_json: ${{ secrets.VAULT_IAP_SA }}
           id_token_audience: ${{ secrets.VAULT_IAP_CLIENT_ID }}
@@ -51,6 +51,13 @@ jobs:
           extraHeaders: "Authorization: Bearer ${{ steps.oidc.outputs.id_token }}"
           secrets: |
             ${{ secrets.VAULT_SECRET_PATH }} | password;
+      
+      - name: Google Auth (AR Token)
+        id: google-auth-ar
+        uses: google-github-actions/auth@v3
+        with:
+          credentials_json: ${{ steps.vault.outputs.password }}
+          project_id: ${{ secrets.ARTIFACT_PROJECT_ID }}
 
       - name: Build and release Python package for each tag
         shell: bash
@@ -78,14 +85,13 @@ jobs:
             uv build --quiet
 
             # Push to artifact registry
-            # Note skip-existing was removed in 6.2.0 of Twine
-            twine upload dist/* \
-              --repository-url ${{ secrets.ARTIFACT_REGISTRY_URL }} \
-              --username ${{ secrets.ARTIFACT_REGISTRY_USERNAME }} \
-              --password "${{ steps.vault.outputs.password }}" \
-              --non-interactive \
-              --disable-progress-bar \
-              --skip-existing
+            uv publish dist/* \
+                --publish-url "${{ secrets.ARTIFACT_REGISTRY_URL }}" \
+                --username "${{ secrets.ARTIFACT_REGISTRY_USERNAME }}" \
+                --password "${{ steps.vault.outputs.password }}" \
+                --check-url "${{ secrets.ARTIFACT_REGISTRY_CHECK_URL }}" \
+                --keyring-provider subprocess \
+                || echo "Failed to publish $tag, continuing..."
 
             # Clean up
             cd ..
